apiVersion: v1
kind: Serivce
metadate:
  name: website-service
  labels:
    app: static-website
  namespace: default    
spec:
  selector:
    app: static-website
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
