apiVersion: v1
kind: Service
metadata:
  labels:
    app: site-demo
  name: site-demo-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: site-demo
  type: NodePort
