apiVersion: apps/v1
kind: Deployment
metadata:
  name: webiste-deployment
  labels:
    app: webiste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webiste
  template:
    metadata:
      labels:
        app: website
    spec:
      container:
        - name: nginx
          image: nginx
          
