apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: site-demo
  name: site-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-demo
  template:
    metadata:
      labels:
        app: site-demo
    spec:
      containers:
      - image: localhost:32000/mysite:registry
        imagePullPolicy: Always
        name: mysite
