apiVersion: apps/v1
kind: Deployment
metadata:
  name: webiste-deployment
  labels:
    app: static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      container:
        - name: nginx
          image: nginx
          
