apiVersion: apps/v1
kind: Deployment
metadata:
  name: webiste-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      container:
        - name: nginx
          image: nginx
          
