apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-site
  name: static-site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - image: localhost:32000/static-site:v0.0.1
        name: static-site
